name: DigitalBits Core Prometheus Exporter

on: push
jobs:
  publish_gh_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0' 
    - name: Github Tag Bump
      id: bump_version
      uses: anothrNick/github-tag-action@1.46.0
      env:
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: main,master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false  
          
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.bump_version.outputs.tag }}
        bodyFile: "README.md"
        token: ${{ secrets.GITHUB_TOKEN }}   

  darwin_build_publish:
    needs: publish_gh_release
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install prometheus_client

    - name: Get Latest Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1

    - name: Build Binaries
      run: |
        pyinstaller -wF digitalbits_core_prometheus_exporter/exporter.py
        mv dist/exporter dist/prometheus_exporter-${{ steps.previoustag.outputs.tag }}-darwin-amd64

    - name: Prepare tarball
      run: |
        tar -zcvf digitalbits-core-prometheus-exporter_${{ steps.previoustag.outputs.tag }}_darwin-amd64.tar.gz -C dist prometheus_exporter-${{ steps.previoustag.outputs.tag }}-darwin-amd64

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "digitalbits-core-prometheus-exporter_${{ steps.previoustag.outputs.tag }}_darwin-amd64.tar.gz"
        tag: ${{ steps.previoustag.outputs.tag }}
        bodyFile: "README.md"
        omitBodyDuringUpdate: true
        token: ${{ secrets.GITHUB_TOKEN }}

  windows_build_publish:
    needs: publish_gh_release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install prometheus_client
    
    - name: Get Latest Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1

    - name: Build Binaries
      run: |
        pyinstaller -wF digitalbits_core_prometheus_exporter/exporter.py
        mv dist\exporter.exe dist\prometheus_exporter-${{ steps.previoustag.outputs.tag }}-windows-amd64.exe

    - name: Prepare zip archive
      run: |
        Compress-Archive dist\prometheus_exporter-${{ steps.previoustag.outputs.tag }}-windows-amd64.exe digitalbits-core-prometheus-exporter_${{ steps.previoustag.outputs.tag }}_windows-amd64.zip

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "digitalbits-core-prometheus-exporter_${{ steps.previoustag.outputs.tag }}_windows-amd64.zip"
        tag: ${{ steps.previoustag.outputs.tag }}
        bodyFile: "README.md"
        omitBodyDuringUpdate: true
        token: ${{ secrets.GITHUB_TOKEN }}
  
  linux_rpm_deb:
    needs: publish_gh_release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get Latest Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cloudsmith-cli==0.26.0
        pip uninstall click -y
        pip install click==7.1.2
        pip install pyinstaller
        pip install prometheus_client
        sudo apt-get install -y ruby ruby-dev rubygems build-essential alien
        sudo gem install --no-document fpm

    - name: Build Binaries
      run: |
        pyinstaller -wF digitalbits_core_prometheus_exporter/exporter.py
        mv dist/exporter dist/prometheus_exporter-${{ steps.previoustag.outputs.tag }}-linux-amd64

    - name: Prepare tarball
      run: |
        tar -zcvf digitalbits-core-prometheus-exporter_${{ steps.previoustag.outputs.tag }}_linux-amd64.tar.gz -C dist prometheus_exporter-${{ steps.previoustag.outputs.tag }}-linux-amd64
    
    - name: Make .rpm package
      run: |
        fpm -f -s dir -t deb -n digitalbits-core-prometheus-exporter -v ${{ steps.previoustag.outputs.tag }} digitalbits_core_prometheus_exporter/=/opt/digitalbits-core-prometheus-exporter/ \
        digitalbits_core_prometheus_exporter/digitalbits-core-prometheus-exporter.service=/etc/systemd/system/digitalbits-core-prometheus-exporter.service \
        digitalbits_core_prometheus_exporter/datadog.yaml=/etc/datadog-agent/conf.d/prometheus.d/conf.yaml

    - name: Make .deb package 
      run: | 
        sudo alien -r -k digitalbits-core-prometheus-exporter_${{ steps.previoustag.outputs.tag }}_amd64.deb

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "digitalbits-core-prometheus-exporter-${{ steps.previoustag.outputs.tag }}*,digitalbits-core-prometheus-exporter_${{ steps.previoustag.outputs.tag }}*"
        tag: ${{ steps.previoustag.outputs.tag }}
        bodyFile: "README.md"
        omitBodyDuringUpdate: true
        token: ${{ secrets.GITHUB_TOKEN }}